apiVersion: v1
kind: Template
metadata:
  name: topological-inventory
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: topological-inventory
    spec:
      envName: ${ENV_NAME}
      deployments:
      - name: google-operations
        minReplicas: ${{MIN_REPLICAS}}
        webServices:
          public:
            enabled: false
          private:
            enabled: false
        podSpec:
          image: ${IMAGE}:${IMAGE_TAG}
          env:
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: METRICS_PORT
            value: ${METRICS_PORT}
          - name: SOURCES_HOST
            value: ${SOURCES_HOST}
          - name: SOURCES_PORT
            value: ${SOURCES_PORT}
          - name: SOURCES_SCHEME
            value: ${SOURCES_SCHEME}
          - name: UPDATE_SOURCES_VIA_API
            value: ${UPDATE_SOURCES_VIA_API}
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - find /tmp -mmin -60 2>/dev/null | grep healthy
          initialDelaySeconds: 1800
          periodSeconds: 300
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
      kafkaTopics:
        - topicName: platform.sources.status
          partitions: 3
          replicas: 3
        - topicName: platform.topological-inventory.operations-google
          partitions: 3
          replicas: 3
parameters:
- name: CPU_LIMIT
  value: 200m
- name: CPU_REQUEST
  value: 100m
- description: Clowder ENV
  name: ENV_NAME
  required: true
- description: Image
  name: IMAGE
  value: quay.io/cloudservices/topological-inventory-google
- description: Image tag
  name: IMAGE_TAG
  required: true
- name: LOG_LEVEL
  value: WARN
- name: MEMORY_LIMIT
  value: 200Mi
- name: MEMORY_REQUEST
  value: 100Mi
- description: Prometheus Metrics Port
  displayName: Metrics Port
  name: METRICS_PORT
  value: '9000' # default in ClowdEnvironment CRD
- description: The number of replicas to use for the prometheus deployment
  name: MIN_REPLICAS
  value: '1'
- description: Host to use for the Sources service URL.
  displayName: Sources Service Host
  name: SOURCES_HOST
  required: true
  value: sources-api
- description: Port to use for the Sources service URL.
  displayName: Sources Service Port
  name: SOURCES_PORT
  value: '8000'
- description: Scheme to use for the Sources service URL.
  displayName: Sources Service Scheme
  name: SOURCES_SCHEME
  value: http
- name: UPDATE_SOURCES_VIA_API
  value: ''
